In [2]:
import torch
X=torch.randn(1,10)
W=torch.randn(2,10,requires_grad=True)
X,W

(tensor([[-1.4725,  0.6877, -1.4501,  1.1598,  2.5623, -0.1665,  0.1151, -0.9268,
           0.2999, -3.0379]]),
 tensor([[ 0.2075, -2.2630,  0.2843,  0.2180, -0.0376,  2.1601, -0.3476, -1.7902,
           0.5247, -1.2798],
         [ 1.0575, -0.0278,  1.0430,  0.4226, -0.0381,  0.0781, -1.7617, -0.0425,
           0.5394, -0.5852]], requires_grad=True))

In [6]:
O=torch.sigmoid(X@W.t())
O

tensor([[0.9604, 0.2823]], grad_fn=<SigmoidBackward0>)

In [7]:
import torch.nn.functional as F
# broadcast 11为12
Y= torch.ones(1,2)
loss = F.mse_loss(Y,O)
loss.backward()
W.grad

tensor([[ 2.2231e-03, -1.0382e-03,  2.1893e-03, -1.7509e-03, -3.8683e-03,
          2.5138e-04, -1.7372e-04,  1.3992e-03, -4.5281e-04,  4.5862e-03],
        [ 2.1412e-01, -9.9997e-02,  2.1086e-01, -1.6864e-01, -3.7258e-01,
          2.4213e-02, -1.6733e-02,  1.3477e-01, -4.3614e-02,  4.4173e-01]])