In [10]:
import torch
X=torch.randn(1,10)
W=torch.randn(1,10,requires_grad=True)
X,W

(tensor([[-0.3860, -0.2651, -2.0119, -0.5565,  0.0263,  1.0592, -0.9192,  0.7255,
          -0.2783, -0.1333]]),
 tensor([[-1.0474,  0.7040,  0.0793, -1.9685,  0.7074,  0.9626, -1.1461,  0.7597,
          -0.6921, -3.0445]], requires_grad=True))

In [11]:
O=torch.sigmoid(X@W.t())
O

tensor([[0.9878]], grad_fn=<SigmoidBackward0>)

In [12]:
import torch.nn.functional as F
Y= torch.ones(1,1)
loss = F.mse_loss(Y,O)
loss.backward()
W.grad

tensor([[ 1.1330e-04,  7.7804e-05,  5.9057e-04,  1.6337e-04, -7.7103e-06,
         -3.1091e-04,  2.6983e-04, -2.1295e-04,  8.1683e-05,  3.9117e-05]])

- W-0.001▽W
- W*X =>Y